FROM public.ecr.aws/lambda/python:3.8

# Copy function code
COPY LamdaAuthorizer.py ${LAMBDA_TASK_ROOT}

RUN chmod 755 ${LAMBDA_TASK_ROOT}/LamdaAuthorizer.py

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "LamdaAuthorizer.lambda_handler" ]