org: mbarper
app: crop-image-moi
service: crop-image-moi

frameworkVersion: '2'

plugins:
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stackName: dev-${self:service}-api
  region: us-east-1
  tracing: true
  memorySize: 256
  stage: dev
  deploymentBucket:
    name: moi-deploys
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  api:
    environment:
      S3_BUCKET: !Ref S3Bucket
    handler: app.lambdaHandler
    role: AppRole
    events:
      - http:
          path: /image
          method: POST

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
    AppRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: S3_ACL
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                  Resource:
                    - !Join ['', [!GetAtt S3Bucket.Arn, "/*"]]
                - Effect: Allow
                  Action:
                    - s3:ListBucket
                  Resource:
                    - !GetAtt S3Bucket.Arn
