name: crop-image-moises

on:
  push:
    branches:
      - development
      - master
      
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SLS_KEY: ${{ secrets.SLS_KEY }}
      SLS_SECRET: ${{ secrets.SLS_SECRET }}
      STAGE: ${{ secrets.STAGE }}
      REGION: ${{ secrets.REGION }}
      BUCKET: ${{ secrets.BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the container
        run: docker build .
