name: CI/CD pipeline

on:
  push:
    branches:
      - "*"

jobs:
  generate_tag:
    name: Generate tag
    environment: development
    runs-on: ubuntu-latest
    steps:
      - id: generate_tag
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=registry::557803826724.dkr.ecr.eu-central-1.amazonaws.com/node-lambda
    outputs:
      registry: ${{ steps.generate_tag.outputs.registry }}
      tag: ${{ steps.generate_tag.outputs.tag }}

  build_image:
    name: Build docker image
    needs: [generate_tag]
    uses: ./.github/workflows/build_docker.yml
    with:
      registry: ${{ needs.generate_tag.outputs.registry }}
      tag: ${{ needs.generate_tag.outputs.tag }}
    secrets: inherit 
  
  update_lambda:
    name: Update lambda
    needs: [build_image]
    container: amazon/aws-cli
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Update lambda
        run: aws lambda update-function-code --function-name aircall-default --image-uri ${{ needs.generate_tag.outputs.registry }}:${{ steps.generate_tag.outputs.tag }}