name: CI/CD pipeline

on:
  push:
    branches:
      - "*"
permissions:
  id-token: write
  contents: read

jobs:
  generate_tag:
    name: Generate tag
    environment: development
    runs-on: ubuntu-latest
    steps:
      - id: generate_tag
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=registry::557803826724.dkr.ecr.eu-central-1.amazonaws.com/node-lambda
    outputs:
      registry: ${{ steps.generate_tag.outputs.registry }}
      tag: ${{ steps.generate_tag.outputs.tag }}

  build_image:
    name: Build docker image
    needs: [generate_tag]
    uses: ./.github/workflows/build_docker.yml
    with:
      registry: ${{ needs.generate_tag.outputs.registry }}
      tag: ${{ needs.generate_tag.outputs.tag }}
    secrets: inherit