name: crop-image-moises

on:
  push:
    branches:
      - development
      - master
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the stack
        env:
          SLS_KEY: ${{ secrets.SLS_KEY }}
          SLS_SECRET: ${{ secrets.SLS_SECRET }}
          STAGE: ${{ secrets.STAGE }}
          REGION: ${{ secrets.REGION }}
          BUCKET: ${{ secrets.BUCKET }}
        uses: ./
